# Esterian Conquest: game setup configuration

### Initial game setup. Immutable after game start  ###

players: 4                       # Number of players in game
host: Toys In The Attic BBS      # Host system name  
sysop: Mason Austin Green        # System operator name
launchTime: 2022-08-23 00:30:00  # Game launch, UTC (YEAR-MM-DD 00:00:00) 
ip: localhost                    # Server's IP address
port: 1992                       # Port nummber

# Configurable during gameplay

maintTime: 00:00:00              # First daily maintenance time (24hr format)
maintPeriod: 24                  # Time between maintenance runs (hours)
