# Esterian Conquest: game setup configuration

players: 4                       # Number of platers in game
host: Toys In The Attic BBS      # Host system name  
sysop: Mason Austin Green        # System operator name
launchDate: 2022-08-23           # Day to officialy start the game: YEAR-MM-DD 
maintPeriod: 24                  # Time between maintnance runs (hours)

# Initial welcome message
welcome: Welcome to Esterian Conquest v2.0... Let's get it on!
